cyber_project/cyber_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('webapp.urls')),
    path('admin/', admin.site.urls),
]

cyber_project/webapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.views import LoginView, LogoutView




app_name = 'webapp'
urlpatterns = [
    path('', LoginView.as_view(template_name='webapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logoutpage'),
    #path('', views.IndexView.as_view(), name='index'),
    path('home/', views.indexView, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/results/', views.resultsView, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('last/', views.lastView, name='lastpage'),
    path('password/', views.PasswordsChangeView.as_view(template_name='webapp/password.html'), name='password'),
    path('username/', views.changeUsername, name='username'),
]

cyber_project/webapp/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

cyber_project/webapp/views.py
from django.http import Http404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django import forms
from django.contrib.auth.models import User
#from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'webapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

resultslist = []

@login_required
def indexView(request):
    question = get_object_or_404(Question, pk=4)
    context = {
        'question' : question,
    }
    return render(request, 'webapp/index.html', context)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'webapp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'webapp/results.html'

#@login_required
def resultsView(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    next_question = Question.objects.filter(id__gt=question_id).order_by('id').first()

    context = {
        'question': question,
        'next_question':next_question,
    }

    return render(request, 'webapp/results.html', context)

#@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        resultslist.append(selected_choice)
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'webapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('webapp:results', args=(question.id,)))

#@login_required
def lastView(request):
    latest_question_list = Question.objects.all()
    combined_list = []
    for question, answer in zip(latest_question_list, resultslist):
        combined_list.append((question, answer))

    context = {
        'combined_list' : combined_list,
    }
    return render(request, 'webapp/last.html', context)

#class PasswordsChangeView(LoginRequiredMixin, PasswordChangeView):
class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('webapp:login')


#class UsernameChangeForm(LoginRequiredMixin, forms.ModelForm):
class UsernameChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

#@login_required
def cleanUsername(self):
    username = self.cleaned_data.get('username')
    if User.objects.filter(username=username).exists():
        raise forms.ValidationError("This username is already taken.")
    return username

#@login_required
def changeUsername(request):
    if request.method == 'POST':
        form = UsernameChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('webapp:login') 
    else:
        form = UsernameChangeForm(instance=request.user)
    return render(request, 'webapp/username.html', {'form': form})

cyber_project/webapp/templates/webapp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'webapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

cyber_project/webapp/templates/webapp/index.html
<h1>Hello {{ user.get_username }}!</h1>
<h2>Polls</h2>

<h3>Your daily mood poll</h3>
<button>
    <a href="{% url 'webapp:detail' question.id %}">Start poll</a>
</button>


<h4>Preferences</h4>
<div style="display: flex; flex-direction: column;">
<a href="{% url 'webapp:username' %}">Change your username</a>
<a href="{% url 'webapp:password' %}">Change your password</a>
</div>

cyber_project/webapp/templates/webapp/last.html
<h1>Great, you answered all the questions!</h1>

<h2>Here are your answers for today:</h2>

{% if combined_list %}
    <ul>
    {% for question, answer in combined_list %}
        <li>{{ question.question_text }}</li>
            <ul>
                <li> Your answer: {{ answer}}</li>
            </ul>
    {% endfor %}
    </ul>

{% else %}
    <h3>You did not answer any questions</h3>
{% endif %}


<a href="{% url 'webapp:logoutpage' %}">Log out</a>

cyber_project/webapp/templates/webapp/login.html
<h2>Welcome to do polls!</h2>
<h2>First, log in:</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

cyber_project/webapp/templates/webapp/password.html
<h2>Change your password:</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change password</button>
</form>

cyber_project/webapp/templates/webapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>


{% if next_question %}
    <a href="{% url 'webapp:detail' next_question.id %}">Next question →</a>
{% else %}
    <a href="{% url 'webapp:lastpage' %}">See the results</a>
{% endif %}

cyber_project/webapp/templates/webapp/username.html
<h2>Change your username:</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change username</button>
</form>